title: Gospel Powered Documentation
metadata:
    description: 'All you need to know about installing, modifying and tweaking your Gospel Powered templates and extensions'

taxonomies: [category,tag]
summary:
  size: 300

